### ISSUE TITLE
docker容器启动失败

### ISSUE THREAD

**Issue by foxdad** [OysterQAQ/ACG2vec-docker#2]
博主你好，我拿你文档说明的docker启动,
博主的docker-compose.ymal milvus的代码是注释的
<img width="557" alt="image" src="https://github.com/OysterQAQ/ACG2vec-docker/assets/48538835/cfafc07c-131e-4093-aad4-413a389f3510">

启动这个容器又依赖这个服务，是否需要放开
<img width="389" alt="image" src="https://github.com/OysterQAQ/ACG2vec-docker/assets/48538835/a7a13141-92ba-4d39-856d-93c35e67e3e9">

拿博主配置的docker-compose 会报错 
service "deepix-webapp" depends on undefined service milvus: invalid compose project

博主的docker-compons-yaml的milvus能否增加
我们自己搭建的milvus配置呢，acg2vec-webapp:1.0.0的镜像这个端口配置可以外放吗

**Comment by OysterQAQ** [comment]
可以移除，acg2vec-webapp接口可以外放的。移除milvus原因是不打算在webapp集成向量检索了，只作为特征抽取工具

发件人: foxdad ***@***.***>
日期: 星期二, 2023年9月19日 19:10
收件人: OysterQAQ/ACG2vec-docker ***@***.***>
抄送: Subscribed ***@***.***>
主题: [OysterQAQ/ACG2vec-docker] docker容器启动失败 (Issue #2)

博主你好，我拿你文档说明的docker启动,
博主的docker-compose.ymal milvus的代码是注释的
[image]<https://user-images.githubusercontent.com/48538835/268933770-cfafc07c-131e-4093-aad4-413a389f3510.png>

启动这个容器又依赖这个服务，是否需要放开
[image]<https://user-images.githubusercontent.com/48538835/268933797-a7a13141-92ba-4d39-856d-93c35e67e3e9.png>

拿博主配置的docker-compose 会报错
service "deepix-webapp" depends on undefined service milvus: invalid compose project

博主的docker-compons-yaml的milvus能否增加
我们自己搭建的milvus配置呢，acg2vec-webapp:1.0.0的镜像这个端口配置可以外放吗

―
